[files]
extend-exclude = ["*.webp", "app/src/main/res/values-*/strings.xml", "gradle/wrapper/gradle-wrapper.jar"]

[default.extend-words]
flate = "flate"
Kover = "Kover"
ND = "ND"
ratatui = "ratatui"
