#!/usr/bin/env python3
"""Generate the extension API reference from public Kotlin declarations."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCES = (
    ROOT / "provider/api/src/main/kotlin/dev/agentrelay/provider/api/ExtensionModels.kt",
    ROOT / "provider/api/src/main/kotlin/dev/agentrelay/provider/api/ExtensionSandboxModels.kt",
)
OUTPUT = ROOT / "docs/generated/extension-api.md"
DECLARATION = re.compile(
    r"^(?:data |sealed |value |fun )?(?:class|interface|object|enum class|fun interface)\s+([A-Za-z][A-Za-z0-9_]*)"
)


def render(sources: tuple[Path, ...] = SOURCES) -> str:
    rows: list[tuple[str, str, int, str]] = []
    for source in sources:
        pending: list[str] = []
        in_doc = False
        for number, line in enumerate(source.read_text(encoding="utf-8").splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith("/**"):
                in_doc = True
                pending = [stripped[3:].split("*/", 1)[0].strip(" *")]
                if "*/" in stripped[3:]:
                    in_doc = False
                continue
            if in_doc:
                pending.append(stripped.split("*/", 1)[0].strip(" *"))
                if "*/" in stripped:
                    in_doc = False
                continue
            match = DECLARATION.match(stripped)
            if match and not match.group(1).startswith("_"):
                description = next(
                    (part for part in pending if part),
                    "Contract symbol; see source implementation.",
                )
                rows.append(
                    (match.group(1), source.relative_to(ROOT).as_posix(), number, description)
                )
            pending = []
    rows.sort(key=lambda row: row[0])
    lines = [
        "# Generated extension API reference",
        "",
        "<!-- Generated by scripts/docs/generate_extension_api.py; do not edit. -->",
        "",
        "| Symbol | Source | Description |",
        "| --- | --- | --- |",
    ]
    lines.extend(
        f"| `{name}` | `{path}:{line}` | {description} |" for name, path, line, description in rows
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    expected = render()
    current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
    if args.check:
        if current != expected:
            print(f"generated extension API is stale: {args.output}")
            return 1
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(expected, encoding="utf-8")
    print("extension API reference is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
