#!/usr/bin/env python3
# Copyright (C) Huawei Technologies Co., Ltd. 2026. All rights reserved.
# SPDX-License-Identifier: MIT

"""Generate deterministic Kotlin provider and typed Python API references."""

from __future__ import annotations

import argparse
import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
KOTLIN_SOURCES = (
    ROOT / "provider/api/src/main/kotlin/dev/agentrelay/provider/api/ExtensionModels.kt",
    ROOT / "provider/api/src/main/kotlin/dev/agentrelay/provider/api/ExtensionSandboxModels.kt",
)
PYTHON_SOURCES = (
    ROOT / "scripts/ci/verify_counterexamples.py",
    ROOT / "scripts/ci/verify_formal_evidence.py",
)
OUTPUT = ROOT / "docs/generated/api-reference.md"
KOTLIN_DECLARATION = re.compile(
    r"^(?:(?:data|sealed|value) )?(?:class|interface|object|enum class|fun interface|fun)\s+"
    r"([A-Za-z][A-Za-z0-9_]*)"
)


def kotlin_symbols() -> list[tuple[str, str, int, str]]:
    rows: list[tuple[str, str, int, str]] = []
    for source in KOTLIN_SOURCES:
        pending: list[str] = []
        in_doc = False
        for number, line in enumerate(source.read_text(encoding="utf-8").splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith("/**"):
                in_doc = "*/" not in stripped[3:]
                pending = [stripped[3:].split("*/", 1)[0].strip(" *")]
                continue
            if in_doc:
                pending.append(stripped.split("*/", 1)[0].strip(" *"))
                if "*/" in stripped:
                    in_doc = False
                continue
            match = KOTLIN_DECLARATION.match(stripped)
            if match and not match.group(1).startswith("_"):
                description = next((part for part in pending if part), "Provider API contract.")
                rows.append(
                    (match.group(1), source.relative_to(ROOT).as_posix(), number, description)
                )
            pending = []
    return sorted(rows, key=lambda row: (row[0], row[1], row[2]))


def python_symbols() -> list[tuple[str, str, int, str, str]]:
    rows: list[tuple[str, str, int, str, str]] = []
    for source in PYTHON_SOURCES:
        tree = ast.parse(source.read_text(encoding="utf-8"), filename=str(source))
        for node in tree.body:
            if not isinstance(
                node, (ast.FunctionDef, ast.AsyncFunctionDef)
            ) or node.name.startswith("_"):
                continue
            if node.returns is None or any(
                arg.annotation is None
                for arg in (*node.args.posonlyargs, *node.args.args, *node.args.kwonlyargs)
            ):
                raise ValueError(f"public Python API must be fully typed: {source}:{node.lineno}")
            description = ast.get_docstring(node)
            if not description:
                raise ValueError(f"public Python API needs a docstring: {source}:{node.lineno}")
            signature = ast.unparse(node).split(":", 1)[0]
            rows.append(
                (
                    node.name,
                    source.relative_to(ROOT).as_posix(),
                    node.lineno,
                    signature,
                    description.splitlines()[0],
                )
            )
    return sorted(rows, key=lambda row: (row[0], row[1], row[2]))


def render() -> str:
    lines = [
        "# Generated API reference",
        "",
        "<!-- Generated by scripts/docs/generate_api_reference.py; do not edit. -->",
        "",
        "This reference is generated from the provider Kotlin contracts and typed Python verification interfaces.",
        "",
        "## Kotlin provider contracts",
        "",
        "| Symbol | Source | Description |",
        "| --- | --- | --- |",
    ]
    lines.extend(
        f"| `{name}` | `{path}:{line}` | {description} |"
        for name, path, line, description in kotlin_symbols()
    )
    lines.extend(
        [
            "",
            "## Python verification interfaces",
            "",
            "| Symbol | Signature | Source | Description |",
            "| --- | --- | --- | --- |",
        ]
    )
    lines.extend(
        f"| `{name}` | `{signature}` | `{path}:{line}` | {description} |"
        for name, path, line, signature, description in python_symbols()
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    expected = render()
    current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
    if args.check:
        if current != expected:
            print(f"generated API reference is stale: {args.output}")
            return 1
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(expected, encoding="utf-8")
    print("API reference is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
