#!/usr/bin/env python3
"""Render and validate the human-goal usage workflow catalogue."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any, cast

import yaml

ROOT = Path(__file__).resolve().parents[2]
SCENARIO_DIR = ROOT / "docs" / "workflows" / "scenarios"
WORKFLOW_DIR = ROOT / "docs" / "workflows"
INDEX_PATH = ROOT / "docs" / "WORKFLOWS.md"
GENERATED_MARKER = "<!-- Generated by scripts/docs/render_workflows.py. Do not edit. -->"
SLUG = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
STATUSES = {"verified", "planned"}
LIST_FIELDS = ("preconditions", "automatic", "attention", "recovery")


class ManifestError(ValueError):
    """A usage-workflow manifest is invalid."""


def require_string(mapping: dict[str, Any], key: str, source: Path) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ManifestError(f"{source}: {key} must be a non-empty string")
    return value.strip()


def require_string_list(mapping: dict[str, Any], key: str, source: Path) -> list[str]:
    value = mapping.get(key)
    if not isinstance(value, list) or not value:
        raise ManifestError(f"{source}: {key} must be a non-empty list")
    if not all(isinstance(item, str) and item.strip() for item in value):
        raise ManifestError(f"{source}: {key} must contain only non-empty strings")
    return [cast(str, item).strip() for item in value]


def validate_step(
    raw: Any,
    *,
    source: Path,
    status: str,
    seen_ids: set[str],
) -> dict[str, Any]:
    if not isinstance(raw, dict):
        raise ManifestError(f"{source}: every step must be a mapping")
    step = cast(dict[str, Any], raw)
    step_id = require_string(step, "id", source)
    if not SLUG.fullmatch(step_id) or step_id in seen_ids:
        raise ManifestError(f"{source}: invalid or duplicate step id {step_id!r}")
    seen_ids.add(step_id)
    require_string(step, "title", source)
    require_string(step, "action", source)
    require_string(step, "expected", source)
    screenshot = step.get("screenshot")
    alt = step.get("alt")
    if status == "verified":
        if not isinstance(screenshot, str) or not SLUG.fullmatch(Path(screenshot).stem):
            raise ManifestError(f"{source}: verified step {step_id!r} needs a safe PNG name")
        if Path(screenshot).suffix.lower() != ".png" or Path(screenshot).name != screenshot:
            raise ManifestError(f"{source}: screenshot must be one PNG file name")
        if not isinstance(alt, str) or len(alt.strip()) < 20:
            raise ManifestError(f"{source}: verified step {step_id!r} needs useful alt text")
    elif screenshot is not None or alt is not None:
        raise ManifestError(f"{source}: planned step {step_id!r} cannot claim image evidence")
    return step


def validate_manifest(raw: Any, source: Path) -> dict[str, Any]:
    if not isinstance(raw, dict):
        raise ManifestError(f"{source}: manifest must be a mapping")
    scenario = cast(dict[str, Any], raw)
    scenario_id = require_string(scenario, "id", source)
    if not SLUG.fullmatch(scenario_id) or source.stem != scenario_id:
        raise ManifestError(f"{source}: id must be a safe slug matching the file name")
    require_string(scenario, "title", source)
    require_string(scenario, "summary", source)
    require_string(scenario, "goal", source)
    status = require_string(scenario, "status", source)
    if status not in STATUSES:
        raise ManifestError(f"{source}: status must be one of {sorted(STATUSES)}")
    order = scenario.get("order")
    if not isinstance(order, int) or isinstance(order, bool) or order < 1:
        raise ManifestError(f"{source}: order must be a positive integer")
    for field in LIST_FIELDS:
        require_string_list(scenario, field, source)
    test_id = scenario.get("verified_test")
    if status == "verified" and (not isinstance(test_id, str) or "#" not in test_id):
        raise ManifestError(f"{source}: verified workflows need a test class and method")
    if status == "planned" and test_id is not None:
        raise ManifestError(f"{source}: planned workflows cannot claim a verification test")
    steps = scenario.get("steps")
    if not isinstance(steps, list) or not steps:
        raise ManifestError(f"{source}: steps must be a non-empty list")
    seen_ids: set[str] = set()
    scenario["steps"] = [
        validate_step(step, source=source, status=status, seen_ids=seen_ids) for step in steps
    ]
    return scenario


def load_scenarios(root: Path = SCENARIO_DIR) -> list[dict[str, Any]]:
    sources = sorted(root.glob("*.yml"))
    if not sources:
        raise ManifestError(f"{root}: no workflow manifests found")
    scenarios = [
        validate_manifest(yaml.safe_load(source.read_text(encoding="utf-8")), source)
        for source in sources
    ]
    ids = [cast(str, scenario["id"]) for scenario in scenarios]
    orders = [cast(int, scenario["order"]) for scenario in scenarios]
    if len(ids) != len(set(ids)) or len(orders) != len(set(orders)):
        raise ManifestError("workflow ids and order values must be globally unique")
    return sorted(scenarios, key=lambda scenario: cast(int, scenario["order"]))


def bullets(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items)


def status_text(scenario: dict[str, Any]) -> str:
    if scenario["status"] == "verified":
        if scenario.get("verification_mode") == "synthetic-waiver":
            return (
                "**Status:** Verified from deterministic synthetic evidence under an explicitly "
                "documented temporary waiver. These redacted image files are not real camera or device captures."
            )
        return (
            "**Status:** Verified by the named Android emulator journey on every pull request "
            "and main-branch push."
        )
    return (
        "**Status:** Planned. This page defines the intended attention contract; it does not "
        "claim that the workflow is implemented."
    )


def render_scenario(scenario: dict[str, Any]) -> str:
    scenario_id = cast(str, scenario["id"])
    lines = [
        GENERATED_MARKER,
        "",
        f"# {scenario['title']}",
        "",
        status_text(scenario),
        "",
        cast(str, scenario["summary"]),
        "",
        "## Goal",
        "",
        cast(str, scenario["goal"]),
        "",
        "## Preconditions",
        "",
        bullets(cast(list[str], scenario["preconditions"])),
        "",
        "## Handled automatically",
        "",
        bullets(cast(list[str], scenario["automatic"])),
        "",
        "## Your attention is needed",
        "",
        bullets(cast(list[str], scenario["attention"])),
        "",
        "## Walkthrough",
        "",
    ]
    for number, step in enumerate(cast(list[dict[str, Any]], scenario["steps"]), start=1):
        lines.extend(
            [
                f"### {number}. {step['title']}",
                "",
                f"**Action:** {step['action']}",
                "",
                f"**Expected result:** {step['expected']}",
                "",
            ]
        )
        screenshot = step.get("screenshot")
        if isinstance(screenshot, str):
            lines.extend(
                [
                    f"![{step['alt']}](../assets/workflows/{scenario_id}/{screenshot})",
                    "",
                ]
            )
    lines.extend(
        [
            "## Recovery and fault handling",
            "",
            bullets(cast(list[str], scenario["recovery"])),
            "",
        ]
    )
    if scenario["status"] == "verified":
        if scenario.get("verification_mode") == "synthetic-waiver":
            lines.extend(
                [
                    "## Verification",
                    "",
                    "- Evidence mode: temporary synthetic-evidence waiver; not real camera/device verification",
                    f"- Review manifest: `{scenario['verified_test']}`",
                    "- Evidence: five deterministic redacted PNG review cards, explicitly labeled synthetic",
                    "",
                ]
            )
            return "\n".join(lines)
        lines.extend(
            [
                "## Verification",
                "",
                f"- Instrumented test: `{scenario['verified_test']}`",
                "- Canonical device: Pixel 7 Pro profile, Android API 36",
                "- Locale, time zone, and theme: English (United States), UTC, light theme, normal font scale",
                "- Evidence: reviewed PNG baselines plus current-run captures and image diffs",
                "",
            ]
        )
    return "\n".join(lines)


def render_index(scenarios: list[dict[str, Any]]) -> str:
    lines = [
        GENERATED_MARKER,
        "",
        "# App workflows",
        "",
        "These pages explain Agent Relay in terms of user goals. Each page separates work that "
        "the app performs in the background from decisions that require human attention.",
        "",
        "A **verified** page is backed by a semantic Android emulator journey and reviewed "
        "screenshots. A **planned** page defines intended behavior without presenting fixture "
        "images as implemented product evidence.",
        "",
        "## Workflow catalogue",
        "",
    ]
    for scenario in scenarios:
        status = "Verified" if scenario["status"] == "verified" else "Planned"
        lines.append(
            f"- [{scenario['title']}](workflows/{scenario['id']}.md) - "
            f"**{status}.** {scenario['summary']}"
        )
    lines.extend(
        [
            "",
            "## Evidence policy",
            "",
            "- Captures use synthetic names, endpoints, sessions, commands, and files.",
            "- Release builds contain no documentation fixture or hidden demonstration mode.",
            "- UI actions use Compose semantics; captures come from Android instrumentation.",
            "- Tests wait for asserted conditions instead of fixed sleeps.",
            "- Pull requests retain the generated site, captures, and diffs as workflow artifacts.",
            "",
        ]
    )
    return "\n".join(lines)


def expected_outputs(scenarios: list[dict[str, Any]]) -> dict[Path, str]:
    outputs = {INDEX_PATH: render_index(scenarios)}
    outputs.update(
        {WORKFLOW_DIR / f"{scenario['id']}.md": render_scenario(scenario) for scenario in scenarios}
    )
    return outputs


def write_or_check(outputs: dict[Path, str], check: bool) -> list[Path]:
    changed: list[Path] = []
    for path, text in outputs.items():
        normalized = f"{text.rstrip()}\n"
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == normalized:
            continue
        changed.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(normalized, encoding="utf-8")
    return changed


def remove_stale_pages(scenarios: list[dict[str, Any]], check: bool) -> list[Path]:
    expected = {f"{scenario['id']}.md" for scenario in scenarios}
    stale = [
        path
        for path in WORKFLOW_DIR.glob("*.md")
        if path.name not in expected
        and path.read_text(encoding="utf-8").startswith(GENERATED_MARKER)
    ]
    if not check:
        for path in stale:
            path.unlink()
    return stale


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if rendered pages are stale")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        scenarios = load_scenarios()
        changed = write_or_check(expected_outputs(scenarios), args.check)
        stale = remove_stale_pages(scenarios, args.check)
    except (ManifestError, OSError, yaml.YAMLError) as error:
        print(f"usage workflow error: {error}", file=sys.stderr)
        return 1
    if args.check and (changed or stale):
        for path in changed + stale:
            print(f"usage workflow output is stale: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    action = "checked" if args.check else "rendered"
    print(f"{action} {len(scenarios)} usage workflows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
